### ISSUE TITLE
Is beep.destroy() some JS standard?

### ISSUE THREAD

**Issue by KevinAst** [kapetan/browser-beep#2]
Hello - I have a quick question for you :-)

I noticed your implementation attaches a `destroy()` method to the returned `beep()` function, that performs cleanup.

```js
  beep.destroy = function () {
    if (!options.context) context.close()
  }
```

I was intrigued by this, as it appears to be some standard convention that is presumably invoked by the JavaScript engine (in garbage collection processing).

However, I searched and searched and cannot find any information on this technique.  I asked some of my "expert" JS colleagues, and they know nothing about it.

I even tried a sandbox test, and could **NOT** get the `destroy()` method to be "auto invoked".

As I said, I was intrigued by this.  If it is a legitimate technique, I would like to have it in my tool-belt.  However I cannot see it working.

Is this some JS standard?  Reference please?

Your help is greatly appreciated.

**Comment by kapetan** [comment]
Hi,

It's purely accidental if the `destroy()` method is getting called automatically. As far as I know there is no way to hook into the garbage collection process in the browser. I added the method so you could manually call it and cleanup resources when you were done.

**Comment by KevinAst** [comment]
Thanks Mirza :-)
